---

- name: Create grafana config directory
  ansible.builtin.file:
    path: "/etc/grafana"
    state: directory

- name: Write config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "grafana.ini.j2", dest: "/etc/grafana/grafana.ini" }
    - { src: "ldap.toml.j2", dest: "/etc/grafana/ldap.toml" }





